### ISSUE TITLE
fix: add "overflow: hidden" to the body element

### ISSUE THREAD

**Issue by Jes015** [Jes015/Web-Capture#59]
The windows make that the property "overflow: visible" of the body, displays a scroll in x and y. Remove this.
Add the property "overflow: hidden" to the body.

**Comment by Kehinde13** [comment]
hello,
can i work on this?

**Comment by Jes015** [comment]
> hello, can i work on this?

Hiiii. Sure, you can.

**Comment by Kehinde13** [comment]
Alright, I will work on it today. Anything I need to know before I start

**Comment by Jes015** [comment]
> Alright, I will work on it today. Anything I need to know before I start

Nothing. Thank u <3
