### ISSUE TITLE
feat(RecordingWindow): display video option 

### ISSUE THREAD

**Issue by Jes015** [Jes015/Web-Capture#62]
The video source must not have borders, margin or padding. it should display the video occupying all the window size

**Comment by huilensolis** [comment]
I'll start working on this : )

**Comment by DrxcoDev** [comment]
> La fuente del vídeo no debe tener bordes, márgenes ni relleno. debería mostrar el vídeo ocupando todo el tamaño de la ventana

Porfavor podrias decir en cual archivo estan los ajustes de la fuente de video, así es más fácil de manejarlo

**Comment by Jes015** [comment]
> > La fuente del vídeo no debe tener bordes, márgenes ni relleno. debería mostrar el vídeo ocupando todo el tamaño de la ventana
> 
> Porfavor podrias decir en cual archivo estan los ajustes de la fuente de video, así es más fácil de manejarlo

en `src/components/feature/RecordingWindow`

A lo que me refiero es que el cuadro azul (el espacio total del video) debe ocupar todo el espacio amarillo (el espacio total del contentido de la ventana).
Despues de eso empezare a trabajar con la API de CANVAS para que en el caso de que la ventana sea muy clara, agregar un backdrop que no afecte mucho al color de las letras.
![captura](https://github.com/Jes015/ScreenCapture/assets/120581623/44745cdd-8daf-475f-a7c8-2058ea5e3d47)

**Comment by DrxcoDev** [comment]
> > > La fuente del vídeo no debe tener bordes, márgenes ni relleno. debería mostrar el vídeo ocupando todo el tamaño de la ventana
> > 
> > 
> > Porfavor podrias decir en cual archivo estan los ajustes de la fuente de video, así es más fácil de manejarlo
> 
> en `src/components/feature/RecordingWindow`
> 
> A lo que me refiero es que el cuadro azul (el espacio total del video) debe ocupar todo el espacio amarillo (el espacio total del contentido de la ventana). Despues de eso empezare a trabajar con la API de CANVAS para que en el caso de que la ventana sea muy clara, agregar un backdrop que no afecte mucho al color de las letras. ![captura](https://private-user-images.githubusercontent.com/120581623/300247135-44745cdd-8daf-475f-a7c8-2058ea5e3d47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzQyMzUsIm5iZiI6MTcwNjQzMzkzNSwicGF0aCI6Ii8xMjA1ODE2MjMvMzAwMjQ3MTM1LTQ0NzQ1Y2RkLThkYWYtNDc1Zi1hN2M4LTIwNThlYTVlM2Q0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwOTI1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjFlYmVmMzNjMmNhMzk2NWI3NTNjY2FjMjkyMDE1Y2VhZDYyMDk1ZTU4YWFhOWVjNWE2OWY1YzU2YjQ3YzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PYv6ybfwc5maJOtjDavi3j5Y9bKD2aXAPowfwgxxmPg)

Creo que ya estaría, de todas formas la idea de lo que tienes que hacer te lo he puesto hay, despues lo puedes editar a tu gusto.

**Comment by huilensolis** [comment]
@DrxcoDev estas trabajando en este issue?

**Comment by DrxcoDev** [comment]
> @DrxcoDev estas trabajando en este issue?

Sí

**Comment by huilensolis** [comment]
srry, como no contestaste decidi comenzar a trabajar en el issue : (
